{% set name = "temporal-cache" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6427397ff4126017a83f3838cfcbf2254fae51284ec4550e81547881b1df1d43

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - frozendict >=1.2
    - six >=1.13.0
    - tzlocal >=2.0.0

test:
  imports:
    - temporalcache

about:
  home: http://github.com/timkpaine/temporal-cache
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Time-based cache invalidation
  description: |
    Time-based cache invalidation
  dev_url: https://github.com/timkpaine/temporal-cache
  doc_url: https://temporal-cache.readthedocs.io

extra:
  recipe-maintainers:
    - timkpaine
