{% set name = "temporal-cache" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6dd850359c46bd4a5c59fc3b953f8924e429b1179a351b3508d07c214738b50

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - frozendict >=1.2
    - six >=1.13.0
    - tzlocal >=2.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - temporalcache

about:
  home: http://github.com/timkpaine/temporal-cache
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Time-based cache invalidation
  description: |
    Time-based cache invalidation
  dev_url: https://github.com/timkpaine/temporal-cache
  doc_url: https://temporal-cache.readthedocs.io

extra:
  recipe-maintainers:
    - timkpaine
